name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*" # Trigger only on version tags

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      # Authenticate npm
      - name: Authenticate npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      # Install dependencies and build
      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build # Adjust this if you have a different build script

      # Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
